baseURL = '/'
defaultContentLanguage = 'de'
title = 'Sindlhausen'
theme = 'blowfish'

[[menu.main]]
name = "Dahoam"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Chronik"
pageRef = "/chronik"
weight = 20

[[menu.main]]
name = "Kirch"
pageRef = "/kirch"
weight = 30

[[menu.main]]
name = "Oiwei scho"
pageRef = "/oiwei-scho"
weight = 40

[[menu.main]]
identifier = "wirtschaft"
name = "Wirtschaft"
pageRef = "/wirtschaft"
weight = 50

[[menu.main]]
name = "Landwirtschaft"
pageRef = "/wirtschaft/landwirtschaft"
parent = "wirtschaft"
weight = 51

[[menu.main]]
name = "Imkerei"
pageRef = "/wirtschaft/imkerei"
parent = "wirtschaft"
weight = 52

[[menu.main]]
name = "Jagd"
pageRef = "/wirtschaft/jagd"
parent = "wirtschaft"
weight = 53

[[menu.main]]
name = "Wasser"
pageRef = "/wirtschaft/wasser"
parent = "wirtschaft"
weight = 54

[params]
logo = "images/logo/kirche.jpg"